version: '3.8'

services:
  dsink-app:
    build:
      context: .
      dockerfile: Dockerfile-local
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_LOCATION=classpath:/,file:/app/config/
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads